### ISSUE TITLE
for loops off by 1

### ISSUE THREAD

**Issue by itorrey** [Log1x/bulma.styl#1]
I was going to do a pull request to fix `title` and `subtitle` but I realized this may affect more than just those two.

The direct port from Sass created a hiccup that I noticed in `title` and `subtitle` as it relates to sizes. Stylus' `for` starts at an index of 0 while Sass' `@each` starts at 1. So bulma.styl is generating a class `.is-0` with the value for one.

Should fix it by doing something like
```
for $size, $i in $sizes
    &.is-{$i+1}
```

**Comment by Log1x** [comment]
Good catch! I'll take care of it tonight when I push the latest updates.
