### ISSUE TITLE
Styles missing

### ISSUE THREAD

**Issue by sebmor** [Log1x/bulma.styl#2]
When I install this package, it seems to be missing all of these;

"stylus/utilities/_all"
"stylus/base/_all"
"stylus/elements/_all"
"stylus/components/_all"
"stylus/grid/_all"
"stylus/layout/_all"

the bulma.styl folder in node_modules only has a bulma.styl and a bulma.css

**Comment by Log1x** [comment]
Are you using npm or yarn? I have no issues installing with `yarn add bulma.styl` -- is it grabbing the latest version (0.5.2)?

https://www.npmjs.com/package/bulma.styl

In any case, I'm not sure why it wouldn't be grabbing the entire repo.

Perhaps grab dev-master with `yarn add https://github.com/Log1x/bulma.styl.git` -- I personally run on dev-master as it will have all the latest bug fixes, etc. as I try to keep the version 1:1 with the original Bulma, but translation mishaps do occasionally happen after versioning and npm not letting me override versions can be frustrating when maintaining a fork like this.

**Comment by sebmor** [comment]
was using npm

**Comment by Log1x** [comment]
Going to close this since I never heard back. I'd look into issues with npm as I've pulled this package during build on 10+ websites on different servers with no issues.

**Comment by Log1x** [comment]
I oddly came across this issue today for the first time after extensively using my fork without any issues. It appeared to be a overlook in the `package.json` of it calling for the `styl` folder instead of `stylus`.

Sorry about that.
