### ISSUE TITLE
why source folder ignored？

### ISSUE THREAD

**Issue by willin** [Log1x/bulma.styl#3]
<img width="1202" alt="wx20171009-142745 2x" src="https://user-images.githubusercontent.com/1890238/31326938-1f108434-ac91-11e7-8613-9f046f4b2dac.png">

**Comment by Log1x** [comment]
This is fixed on dev-master. I will push the fix to npm.

**Comment by Log1x** [comment]
Pushed `0.5.31` to npm to fix this issue prior to a new release of Bulma.
