### ISSUE TITLE
Partial includes

### ISSUE THREAD

**Issue by acidjazz** [Log1x/bulma.styl#4]
Is there any simple way to just include certain components/elements?

Just trying to cut down on compilation time and file size.

Potential feature? or something to add to the docs/readme?

**Comment by Log1x** [comment]
Of course.

Assuming you're using something like [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) to compile your Stylus, you can simply do something like:

`@require "~bulma.styl/stylus/components/card"` for example.

Going to close this but feel free to keep commenting on this if you need any help.

**Comment by acidjazz** [comment]
I'm actually using VueJS and Nuxt.js, I found this to be a bit faster in compilation and alot smaller in size:

```stylus
@charset "utf-8"
@import "~bulma.styl/stylus/utilities/_all"
@import "~bulma.styl/stylus/base/_all"
@import "~bulma.styl/stylus/elements/button"
@import "~bulma.styl/stylus/components/modal"
@import "~bulma.styl/stylus/grid/_all"
@import "~bulma.styl/stylus/layout/_all"
```
The components folder is the largest, so its nice to be able to pick and choose from it.  Let me know if you want a PR sample in the readme!
